package com.recco.internal.core.model.feed

enum class FeedSectionType {
    PHYSICAL_ACTIVITY_RECOMMENDATIONS, 
    NUTRITION_RECOMMENDATIONS, 
    MENTAL_WELLBEING_RECOMMENDATIONS,
    SLEEP_RECOMMENDATIONS, 
    PHYSICAL_ACTIVITY_EXPLORE, 
    NUTRITION_EXPLORE, 
    MENTAL_WELLBEING_EXPLORE,
    SLEEP_EXPLORE, 
    PREFERRED_RECOMMENDATIONS, 
    MOST_POPULAR, 
    NEW_CONTENT,
    STARTING_RECOMMENDATIONS;
}