/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.openapi.model

import com.shadowflight.openapi.model.AppUserRecommendationDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param recommendations 
 */
@JsonClass(generateAdapter = true)
data class FeedSectionDTO(

    @Json(name = "type")
    val type: FeedSectionDTO.Type,

    @Json(name = "recommendations")
    val recommendations: kotlin.collections.List<AppUserRecommendationDTO>
) {
    /**
     * 
     *
     * Values: STARTING_RECOMMENDATION,TAILORED_RECOMMENDATION,TAILORED_NUTRITION_RECOMMENDATION,MOST_POPULAR
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "STARTING_RECOMMENDATION") STARTING_RECOMMENDATION("STARTING_RECOMMENDATION"),
        @Json(name = "TAILORED_RECOMMENDATION") TAILORED_RECOMMENDATION("TAILORED_RECOMMENDATION"),
        @Json(name = "TAILORED_NUTRITION_RECOMMENDATION") TAILORED_NUTRITION_RECOMMENDATION("TAILORED_NUTRITION_RECOMMENDATION"),
        @Json(name = "MOST_POPULAR") MOST_POPULAR("MOST_POPULAR");
    }
}

