/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.openapi.api

import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json
import com.shadowflight.openapi.model.ApiErrorDTO
import com.shadowflight.openapi.model.QuestionnaireAnswersDTO
import com.shadowflight.openapi.model.QuestionnaireDTO

interface QuestionnaireApi {

    /**
     * Set user app answers for a questionnaire.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param questionnaireAnswersDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/questionnaire/answers")
    suspend fun answers(@Body questionnaireAnswersDTO: QuestionnaireAnswersDTO): Response<Unit>

    /**
     * Return the associated questionnaire for a given topic.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @param topicId 
     * @return [QuestionnaireDTO]
     */
    @GET("api/v1/me/questionnaire/topics/{topicId}")
    suspend fun getQuestionnaireByTopic(@Path("topicId") topicId: kotlin.Int): Response<QuestionnaireDTO>

    /**
     * Return the onboarding questionnaires.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @return [kotlin.collections.List<QuestionnaireDTO>]
     */
    @GET("api/v1/me/questionnaire/onboarding_questionnaires")
    suspend fun onboarding(): Response<kotlin.collections.List<QuestionnaireDTO>>

    /**
     * Set user app answers for the onboarding questionnaires.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param questionnaireAnswersDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/questionnaire/onboarding_answers")
    suspend fun onboardingAnswers(@Body questionnaireAnswersDTO: kotlin.collections.List<QuestionnaireAnswersDTO>): Response<Unit>
}
