/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.api

import retrofit2.http.*
import retrofit2.Response
import com.shadowflight.core.openapi.model.AppUserDTO

interface AppUserApi {

    /**
     * Return app user.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @return [AppUserDTO]
     */
    @GET("api/v1/me")
    suspend fun get(): Response<AppUserDTO>
}
