/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.api

import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json
import com.shadowflight.core.openapi.model.ApiErrorDTO
import com.shadowflight.core.openapi.model.FeedSectionDTO

interface FeedApi {

    /**
     * Get feed sections.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @return [kotlin.collections.List<FeedSectionDTO>]
     */
    @GET("api/v1/me/feed")
    suspend fun getFeed(): Response<kotlin.collections.List<FeedSectionDTO>>
}
