/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.api

import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json
import com.shadowflight.core.openapi.model.ApiErrorDTO
import com.shadowflight.core.openapi.model.CreateMetricSessionDTO

interface MetricApi {

    /**
     * Log session login event.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @return [Unit]
     */
    @POST("api/v1/me/metric/login")
    suspend fun loginEvent(): Response<Unit>

    /**
     * Log session duration event.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param createMetricSessionDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/metric/session")
    suspend fun sessionEvent(@Body createMetricSessionDTO: CreateMetricSessionDTO): Response<Unit>
}
