/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.api

import com.recco.internal.core.openapi.model.FeedSectionDTO
import retrofit2.Response
import retrofit2.http.*

interface FeedApi {

    /**
     * Get feed sections.
     *
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @return [kotlin.collections.List<FeedSectionDTO>]
     */
    @GET("api/v1/me/feed")
    suspend fun getFeed(): Response<kotlin.collections.List<FeedSectionDTO>>
}
