/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.api

import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json
import com.recco.internal.core.openapi.model.ApiErrorDTO
import com.recco.internal.core.openapi.model.AppUserMetricEventDTO

interface MetricApi {

    /**
     * Log event.
     * 
     * Responses:
     *  - 204: No Content
     *  - 401: Unauthorized
     *
     * @param appUserMetricEventDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/metric")
    suspend fun logEvent(@Body appUserMetricEventDTO: AppUserMetricEventDTO): Response<Unit>
}
