/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.api

import com.recco.internal.core.openapi.model.AppUserMetricEventDTO
import retrofit2.Response
import retrofit2.http.*

interface MetricApi {

    /**
     * Log event.
     *
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param appUserMetricEventDTO
     * @return [Unit]
     */
    @POST("api/v1/me/metric")
    suspend fun logEvent(@Body appUserMetricEventDTO: AppUserMetricEventDTO): Response<Unit>
}
