/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.api

import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json
import com.recco.internal.core.openapi.model.ApiErrorDTO
import com.recco.internal.core.openapi.model.CreateQuestionnaireAnswerDTO
import com.recco.internal.core.openapi.model.QuestionDTO
import com.recco.internal.core.openapi.model.TopicDTO

interface QuestionnaireApi {

    /**
     * Set user app answers for a questionnaire.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param createQuestionnaireAnswerDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/questionnaire/answers")
    suspend fun answers(@Body createQuestionnaireAnswerDTO: kotlin.collections.List<CreateQuestionnaireAnswerDTO>): Response<Unit>

    /**
     * Return the associated questionnaire for a given topic.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @param topic 
     * @return [kotlin.collections.List<QuestionDTO>]
     */
    @GET("api/v1/me/questionnaire/topics/{topic}")
    suspend fun getQuestionnaireByTopic(@Path("topic") topic: TopicDTO): Response<kotlin.collections.List<QuestionDTO>>

    /**
     * Return the onboarding questionnaire.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 200: OK
     *
     * @return [kotlin.collections.List<QuestionDTO>]
     */
    @GET("api/v1/me/questionnaire/onboarding_questionnaires")
    suspend fun onboarding(): Response<kotlin.collections.List<QuestionDTO>>

    /**
     * Set user app answers for the onboarding questionnaires.
     * 
     * Responses:
     *  - 401: Unauthorized
     *  - 204: No Content
     *
     * @param createQuestionnaireAnswerDTO 
     * @return [Unit]
     */
    @POST("api/v1/me/questionnaire/onboarding_answers")
    suspend fun onboardingAnswers(@Body createQuestionnaireAnswerDTO: kotlin.collections.List<CreateQuestionnaireAnswerDTO>): Response<Unit>
}
