/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param isOnboardingQuestionnaireCompleted 
 */
@JsonClass(generateAdapter = true)
data class AppUserDTO(

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "isOnboardingQuestionnaireCompleted")
    val isOnboardingQuestionnaireCompleted: kotlin.Boolean
)
