/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param questionId 
 * @param type 
 * @param multichoice 
 * @param numeric 
 */
@JsonClass(generateAdapter = true)
data class CreateQuestionnaireAnswerDTO(

    @Json(name = "questionId")
    val questionId: kotlin.String,

    @Json(name = "type")
    val type: Type,

    @Json(name = "multichoice")
    val multichoice: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "numeric")
    val numeric: kotlin.Double? = null
) {
    /**
     * 
     *
     * Values: MULTICHOICE,NUMERIC
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "multichoice") MULTICHOICE("multichoice"),
        @Json(name = "numeric") NUMERIC("numeric");
    }
}

