/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxValue 
 * @param minValue 
 * @param format 
 */
@JsonClass(generateAdapter = true)
data class NumericQuestionDTO(

    @Json(name = "maxValue")
    val maxValue: kotlin.Int,

    @Json(name = "minValue")
    val minValue: kotlin.Int,

    @Json(name = "format")
    val format: NumericQuestionDTO.Format
) {
    /**
     * 
     *
     * Values: HUMAN_HEIGHT,HUMAN_WEIGHT,INTEGER,DECIMAL
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "HUMAN_HEIGHT") HUMAN_HEIGHT("HUMAN_HEIGHT"),
        @Json(name = "HUMAN_WEIGHT") HUMAN_WEIGHT("HUMAN_WEIGHT"),
        @Json(name = "INTEGER") INTEGER("INTEGER"),
        @Json(name = "DECIMAL") DECIMAL("DECIMAL");
    }
}

