/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param categoriesIds 
 * @param answers 
 */
@JsonClass(generateAdapter = true)
data class QuestionnaireAnswersDTO(

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "categoriesIds")
    val categoriesIds: kotlin.collections.List<kotlin.Int>,

    @Json(name = "answers")
    val answers: kotlin.collections.List<CreateQuestionnaireAnswerDTO>
)
