/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.core.openapi.model

import com.shadowflight.core.openapi.model.ContentIdDTO
import com.shadowflight.core.openapi.model.ContentTypeDTO
import com.shadowflight.core.openapi.model.RatingDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentId 
 * @param contentType 
 * @param rating 
 */
@JsonClass(generateAdapter = true)
data class UpdateRatingDTO(

    @Json(name = "contentId")
    val contentId: ContentIdDTO,

    @Json(name = "contentType")
    val contentType: ContentTypeDTO,

    @Json(name = "rating")
    val rating: RatingDTO
)
