/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.openapi.model

import com.shadowflight.openapi.model.ContentIdDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param rating 
 * @param status 
 * @param headline 
 * @param lead 
 * @param imageUrl 
 */
@JsonClass(generateAdapter = true)
data class AppUserRecommendationDTO(

    @Json(name = "id")
    val id: ContentIdDTO,

    @Json(name = "type")
    val type: AppUserRecommendationDTO.Type,

    @Json(name = "rating")
    val rating: AppUserRecommendationDTO.Rating,

    @Json(name = "status")
    val status: AppUserRecommendationDTO.Status,

    @Json(name = "headline")
    val headline: kotlin.String,

    @Json(name = "lead")
    val lead: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null
) {
    /**
     * 
     *
     * Values: ARTICLES
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "articles") ARTICLES("articles");
    }
    /**
     * 
     *
     * Values: LIKE,DISLIKE,NOT_RATED
     */
    @JsonClass(generateAdapter = false)
    enum class Rating(val value: kotlin.String) {
        @Json(name = "like") LIKE("like"),
        @Json(name = "dislike") DISLIKE("dislike"),
        @Json(name = "not_rated") NOT_RATED("not_rated");
    }
    /**
     * 
     *
     * Values: NO_INTERACTION,VIEWED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "no_interaction") NO_INTERACTION("no_interaction"),
        @Json(name = "viewed") VIEWED("viewed");
    }
}

