/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.shadowflight.openapi.model

import com.shadowflight.openapi.model.ContentIdDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentId 
 * @param contentType 
 * @param status 
 */
@JsonClass(generateAdapter = true)
data class UpdateStatusDTO(

    @Json(name = "contentId")
    val contentId: ContentIdDTO,

    @Json(name = "contentType")
    val contentType: UpdateStatusDTO.ContentType,

    @Json(name = "status")
    val status: UpdateStatusDTO.Status
) {
    /**
     * 
     *
     * Values: ARTICLES
     */
    @JsonClass(generateAdapter = false)
    enum class ContentType(val value: kotlin.String) {
        @Json(name = "articles") ARTICLES("articles");
    }
    /**
     * 
     *
     * Values: NO_INTERACTION,VIEWED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "no_interaction") NO_INTERACTION("no_interaction"),
        @Json(name = "viewed") VIEWED("viewed");
    }
}

