/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errorCode 
 * @param message 
 * @param traceId 
 */
@JsonClass(generateAdapter = true)
data class ApiErrorDTO(

    @Json(name = "errorCode")
    val errorCode: ApiErrorDTO.ErrorCode,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "traceId")
    val traceId: kotlin.String
) {
    /**
     * 
     *
     * Values: UNKNOWN,RESOURCE_NOT_FOUND,UNAUTHORIZED,APP_DISABLED,BAD_REQUEST,CONFLICT
     */
    @JsonClass(generateAdapter = false)
    enum class ErrorCode(val value: kotlin.String) {
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN"),
        @Json(name = "RESOURCE_NOT_FOUND") RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
        @Json(name = "UNAUTHORIZED") UNAUTHORIZED("UNAUTHORIZED"),
        @Json(name = "APP_DISABLED") APP_DISABLED("APP_DISABLED"),
        @Json(name = "BAD_REQUEST") BAD_REQUEST("BAD_REQUEST"),
        @Json(name = "CONFLICT") CONFLICT("CONFLICT");
    }
}

