/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.core.openapi.model

import com.recco.core.openapi.model.AppUserMetricActionDTO
import com.recco.core.openapi.model.AppUserMetricCategoryDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param category 
 * @param action 
 * @param `value` 
 */
@JsonClass(generateAdapter = true)
data class AppUserMetricEventDTO(

    @Json(name = "category")
    val category: AppUserMetricCategoryDTO,

    @Json(name = "action")
    val action: AppUserMetricActionDTO,

    @Json(name = "value")
    val `value`: kotlin.String? = null
)
