/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param seconds 
 */
@JsonClass(generateAdapter = true)
data class CreateMetricSessionDTO(

    @Json(name = "seconds")
    val seconds: kotlin.Int
)
