/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.core.openapi.model

import com.recco.core.openapi.model.FeedSectionStateDTO
import com.recco.core.openapi.model.FeedSectionTypeDTO
import com.recco.core.openapi.model.TopicDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param state 
 * @param locked 
 * @param topic 
 */
@JsonClass(generateAdapter = true)
data class FeedSectionDTO(

    @Json(name = "type")
    val type: FeedSectionTypeDTO,

    @Json(name = "state")
    val state: FeedSectionStateDTO,

    @Json(name = "locked")
    val locked: kotlin.Boolean,

    @Json(name = "topic")
    val topic: TopicDTO? = null
)
