/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.recco.internal.core.openapi.model.ContentIdDTO
import com.recco.internal.core.openapi.model.RatingDTO
import com.recco.internal.core.openapi.model.StatusDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param rating 
 * @param status 
 * @param bookmarked 
 * @param headline 
 * @param theme 
 * @param audioUrl 
 * @param duration The estimated duration in seconds to read this article
 * @param transcription 
 * @param description 
 * @param dynamicImageResizingUrl 
 * @param imageAlt 
 */
@JsonClass(generateAdapter = true)
data class AppUserAudioDTO(

    @Json(name = "id")
    val id: ContentIdDTO,

    @Json(name = "rating")
    val rating: RatingDTO,

    @Json(name = "status")
    val status: StatusDTO,

    @Json(name = "bookmarked")
    val bookmarked: kotlin.Boolean,

    @Json(name = "headline")
    val headline: kotlin.String,

    @Json(name = "theme")
    val theme: AppUserAudioDTO.Theme,

    @Json(name = "audioUrl")
    val audioUrl: kotlin.String,

    /* The estimated duration in seconds to read this article */
    @Json(name = "duration")
    val duration: kotlin.Int,

    @Json(name = "transcription")
    val transcription: kotlin.Boolean,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "dynamicImageResizingUrl")
    val dynamicImageResizingUrl: kotlin.String? = null,

    @Json(name = "imageAlt")
    val imageAlt: kotlin.String? = null
) {
    /**
     * 
     *
     * Values: MEDITATION,RELAXATION_EXERCISE
     */
    @JsonClass(generateAdapter = false)
    enum class Theme(val value: kotlin.String) {
        @Json(name = "meditation") MEDITATION("meditation"),
        @Json(name = "relaxation_exercise") RELAXATION_EXERCISE("relaxation_exercise");
    }
}

