/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.recco.internal.core.openapi.model.ContentIdDTO
import com.recco.internal.core.openapi.model.RatingDTO
import com.recco.internal.core.openapi.model.StatusDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param rating 
 * @param status 
 * @param bookmarked 
 * @param headline 
 * @param category 
 * @param videoUrl 
 * @param duration The estimated duration in seconds to read this article
 * @param description 
 * @param disclaimer 
 * @param warning 
 * @param dynamicImageResizingUrl 
 * @param imageAlt 
 */
@JsonClass(generateAdapter = true)
data class AppUserVideoDTO(

    @Json(name = "id")
    val id: ContentIdDTO,

    @Json(name = "rating")
    val rating: RatingDTO,

    @Json(name = "status")
    val status: StatusDTO,

    @Json(name = "bookmarked")
    val bookmarked: kotlin.Boolean,

    @Json(name = "headline")
    val headline: kotlin.String,

    @Json(name = "category")
    val category: AppUserVideoDTO.Category,

    @Json(name = "videoUrl")
    val videoUrl: kotlin.String,

    /* The estimated duration in seconds to read this article */
    @Json(name = "duration")
    val duration: kotlin.Int,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "disclaimer")
    val disclaimer: kotlin.String? = null,

    @Json(name = "warning")
    val warning: kotlin.String? = null,

    @Json(name = "dynamicImageResizingUrl")
    val dynamicImageResizingUrl: kotlin.String? = null,

    @Json(name = "imageAlt")
    val imageAlt: kotlin.String? = null
) {
    /**
     * 
     *
     * Values: EXERCISE,MEDITATION
     */
    @JsonClass(generateAdapter = false)
    enum class Category(val value: kotlin.String) {
        @Json(name = "exercise") EXERCISE("exercise"),
        @Json(name = "meditation") MEDITATION("meditation");
    }
}

