/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.recco.internal.core.openapi.model.StyleDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param clientUserId 
 * @param isOnboardingQuestionnaireCompleted 
 * @param appStyle 
 * @param appRedirectUrl 
 */
@JsonClass(generateAdapter = true)
data class AppUserDTO(

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "clientUserId")
    val clientUserId: kotlin.String,

    @Json(name = "isOnboardingQuestionnaireCompleted")
    val isOnboardingQuestionnaireCompleted: kotlin.Boolean,

    @Json(name = "appStyle")
    val appStyle: StyleDTO? = null,

    @Json(name = "appRedirectUrl")
    val appRedirectUrl: kotlin.String? = null
)
