/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *      CSS Hex Codes     The AA value (alpha) in #RRGGBBAA can range from the lowest value possible (00) to the highest value possible (FF) 
 *
 * @param primary 
 * @param onPrimary 
 * @param background 
 * @param onBackground 
 * @param accent 
 * @param onAccent 
 * @param illustration 
 * @param illustrationOutline 
 */
@JsonClass(generateAdapter = true)
data class ColorsDTO(

    @Json(name = "primary")
    val primary: kotlin.String,

    @Json(name = "onPrimary")
    val onPrimary: kotlin.String,

    @Json(name = "background")
    val background: kotlin.String,

    @Json(name = "onBackground")
    val onBackground: kotlin.String,

    @Json(name = "accent")
    val accent: kotlin.String,

    @Json(name = "onAccent")
    val onAccent: kotlin.String,

    @Json(name = "illustration")
    val illustration: kotlin.String,

    @Json(name = "illustrationOutline")
    val illustrationOutline: kotlin.String
)
