/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: PHYSICAL_ACTIVITY_RECOMMENDATIONS,NUTRITION_RECOMMENDATIONS,MENTAL_WELLBEING_RECOMMENDATIONS,SLEEP_RECOMMENDATIONS,PREFERRED_RECOMMENDATIONS,MOST_POPULAR,NEW_CONTENT,PHYSICAL_ACTIVITY_EXPLORE,NUTRITION_EXPLORE,MENTAL_WELLBEING_EXPLORE,SLEEP_EXPLORE,STARTING_RECOMMENDATIONS
 */
@Suppress("RemoveRedundantQualifierName")
@JsonClass(generateAdapter = false)
enum class FeedSectionTypeDTO(val value: kotlin.String) {

    @Json(name = "physical_activity_recommendations")
    PHYSICAL_ACTIVITY_RECOMMENDATIONS("physical_activity_recommendations"),

    @Json(name = "nutrition_recommendations")
    NUTRITION_RECOMMENDATIONS("nutrition_recommendations"),

    @Json(name = "mental_wellbeing_recommendations")
    MENTAL_WELLBEING_RECOMMENDATIONS("mental_wellbeing_recommendations"),

    @Json(name = "sleep_recommendations")
    SLEEP_RECOMMENDATIONS("sleep_recommendations"),

    @Json(name = "preferred_recommendations")
    PREFERRED_RECOMMENDATIONS("preferred_recommendations"),

    @Json(name = "most_popular")
    MOST_POPULAR("most_popular"),

    @Json(name = "new_content")
    NEW_CONTENT("new_content"),

    @Json(name = "physical_activity_explore")
    PHYSICAL_ACTIVITY_EXPLORE("physical_activity_explore"),

    @Json(name = "nutrition_explore")
    NUTRITION_EXPLORE("nutrition_explore"),

    @Json(name = "mental_wellbeing_explore")
    MENTAL_WELLBEING_EXPLORE("mental_wellbeing_explore"),

    @Json(name = "sleep_explore")
    SLEEP_EXPLORE("sleep_explore"),

    @Json(name = "starting_recommendations")
    STARTING_RECOMMENDATIONS("starting_recommendations");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value
}
