/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type
 * @param state
 * @param topic
 */
@JsonClass(generateAdapter = true)
data class FeedSectionDTO(

    @Json(name = "type")
    val type: FeedSectionTypeDTO,

    @Json(name = "state")
    val state: FeedSectionStateDTO,

    @Json(name = "topic")
    val topic: TopicDTO? = null
)
