/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tokenId PAT's id
 */
@JsonClass(generateAdapter = true)
data class PATReferenceDeleteDTO(

    /* PAT's id */
    @Json(name = "tokenId")
    val tokenId: kotlin.String
)
