/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param questionnaireId
 * @param id
 * @param index
 * @param text
 * @param type
 * @param multiChoice
 * @param multiChoiceSelectedIds
 * @param numeric
 * @param numericSelected
 */
@JsonClass(generateAdapter = true)
data class QuestionDTO(

    @Json(name = "questionnaireId")
    val questionnaireId: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "index")
    val index: kotlin.Int,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "type")
    val type: QuestionAnswerTypeDTO,

    @Json(name = "multiChoice")
    val multiChoice: MultiChoiceQuestionDTO? = null,

    @Json(name = "multiChoiceSelectedIds")
    val multiChoiceSelectedIds: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "numeric")
    val numeric: NumericQuestionDTO? = null,

    @Json(name = "numericSelected")
    val numericSelected: kotlin.Double? = null
)
