/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.recco.internal.core.openapi.model.AndroidFontDTO
import com.recco.internal.core.openapi.model.ColorsDTO
import com.recco.internal.core.openapi.model.IOSFontDTO
import com.recco.internal.core.openapi.model.WebFontDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param darkColors 
 * @param lightColors 
 * @param iosFont 
 * @param androidFont 
 * @param webFont 
 * @param isPredefined 
 */
@JsonClass(generateAdapter = true)
data class StyleDTO(

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "darkColors")
    val darkColors: ColorsDTO,

    @Json(name = "lightColors")
    val lightColors: ColorsDTO,

    @Json(name = "iosFont")
    val iosFont: IOSFontDTO,

    @Json(name = "androidFont")
    val androidFont: AndroidFontDTO,

    @Json(name = "webFont")
    val webFont: WebFontDTO,

    @Json(name = "isPredefined")
    val isPredefined: kotlin.Boolean
)
