/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.recco.internal.core.openapi.model.AndroidFontDTO
import com.recco.internal.core.openapi.model.ColorsDTO
import com.recco.internal.core.openapi.model.IOSFontDTO
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param darkColors 
 * @param lightColors 
 * @param iosFont 
 * @param androidFont 
 */
@JsonClass(generateAdapter = true)
data class StyleDTO(

    @Json(name = "darkColors")
    val darkColors: ColorsDTO,

    @Json(name = "lightColors")
    val lightColors: ColorsDTO,

    @Json(name = "iosFont")
    val iosFont: IOSFontDTO,

    @Json(name = "androidFont")
    val androidFont: AndroidFontDTO
)
