/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.recco.internal.core.openapi.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: PHYSICAL_ACTIVITY,NUTRITION,MENTAL_WELLBEING,SLEEP
 */
@Suppress("RemoveRedundantQualifierName")
@JsonClass(generateAdapter = false)
enum class TopicDTO(val value: kotlin.String) {

    @Json(name = "physical_activity")
    PHYSICAL_ACTIVITY("physical_activity"),

    @Json(name = "nutrition")
    NUTRITION("nutrition"),

    @Json(name = "mental_wellbeing")
    MENTAL_WELLBEING("mental_wellbeing"),

    @Json(name = "sleep")
    SLEEP("sleep");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value
}
