---
name: build-release-APK
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      CLIENT_SECRET: secrets.CLIENT_SECRET_PROD_SHOWCASE
    strategy:
      matrix:
        os: [ "ubuntu-22.04" ]
    steps:
      - name: "Checkout repository..."
        uses: "actions/checkout@v3"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          java-package: "jdk"
          distribution: "corretto"
          cache: "gradle"
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace
      - name: "Archive APK"
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: |
            showcase/build/outputs/apk/release/showcase-release.apk
