---
name: pull-request
on:
  pull_request:
    branches: [ main ]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository..."
        uses: "actions/checkout@v3"

      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          java-package: "jdk"
          distribution: "corretto"
          cache: "gradle"

      - name: "Run lint"
        run: ./gradlew lint

      - name: "Run spotless"
        run: ./gradlew spotlessCheck --no-configuration-cache

      - name: "Run unit tests"
        run: ./gradlew test

      - name: "Archive reports"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: archive_reports
          path: |
            internal/core/**/build/reports/
            internal/feature/**/build/reports/
